### ISSUE TITLE
Wrong warning message sent from Github resource of type source,condition,target

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#1035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Current Updatecli run show the wrong warning message for source/condition/target which shouldn't be updated

```
#######################
# BUMP GOLANG VERSION #
#######################


SOURCES
=======
WARNING: The kind "github" for actions is deprecated in favor of 'github/pullrequest'
```

### Expected Behavior

No message should be displayed

### Environment

```markdown
- OS:
- updatecli:
```

**Comment by dduportal** [comment]
@olblak do you have a reproduction case? Because I can't reproduce (unless I do not update the kind of actions of course)?

The last build on the main branch here: https://github.com/updatecli/updatecli/actions/runs/3677575590/jobs/6219718689 does not show such warning and I can't either in my "upgrade" PR  in https://github.com/jenkins-infra/jenkins-infra/pull/2536#event-8014625595 🤔

**Comment by dduportal** [comment]
@olblak shared the following reproduction: https://github.com/updatecli/updatecli/actions/runs/3677958042/jobs/6220607534
