### ISSUE TITLE
github/pullrequest Auth failure poisons retries

### ISSUE THREAD

**Issue by waciumawanjohi** [updatecli/updatecli#1162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the `github/pullrequest` action is run with an incorrect username, the action will fail with the message

```
ERROR: something went wrong in target "bumpKo" : "authorization failed"
```

If the username is fixed, and the action rerun, the action will fail with the message:

```
Pipeline ... failed
Skipping due to:
        action stage:   "Head sha can't be blank, Base sha can't be blank, No commits between BRANCH and updatecli_SOME_SHA, Head ref must be a branch"
```

To address this, users must delete a temp folder that updateCLI has created locally. This
1. is suprising
2. requires a stronger mental model of the internal operation of updateCLI than users are likely to have
3. is not idempotent: reruns of the action with the incorrect username will yield different error messages; first about auth and then about no commits of difference

### Expected Behavior

On fixing the username and rerunning the update, the update should succeed.

### Steps To Reproduce

- Define a manifest with an action with `kind: github/pullrequest`
- In scms, define a `username` which does not match the (valid) `token`
- Run the action.
- Fix the `username`.
- Rerun the action

### Environment

```markdown
- OS: OSX 13.1 (ARM) 
- updatecli:
  - Application:    0.44.2
  - Golang     :    1.19.5 linux/amd64
  - Build Time :    2023-02-13T18:01:23Z
```

**Comment by olblak** [comment]
Thanks @waciumawanjohi for opening this issue. It's definitely a bug in the pipeline that should be solved.
What you notice with the pullrequest is the consequence of the bug

At the moment, Updatecli only executes git operation if a target is changed, the code is [here](https://github.com/updatecli/updatecli/blob/main/pkg/core/pipeline/target/main.go#L98L103)

So what happened was:
* First time, Updatecli is executed, detects changes but fail to push them due to permission issue
* Second time, Updatecli is executed, do not detect changes as already done in the first execution and exit with a "success"

IMHO the improvement should be, if the target has a scmid specified then we compare the local repository with the remote one and run git push operation if needed.
