### ISSUE TITLE
Feature Request: Conditional Target

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#1385]
### Is your feature request related to a problem?

At the moment all conditions must pass before reaching the target stage.
If at least one condition fails then all targets are skipped.
The reasoning was because we designed one pipeline per manifest so it didn't make sense to proceed if at least one condition failed.

The reality is we can have multiple pipeline within a manifest as we can have multiple actions.

It worth mentioning that we can "revert" the expected result of condition using the boolean `failwhen`

### Solution you'd like

In this pullrequest, @dcoraboeuf suggested to add a new target setting 
https://github.com/updatecli/updatecli/pull/1382 
such as 

```
conditions:
    versionExist:
        kind: yaml
        spec:
            ...
targets:
    version:
        kind: yaml
        conditions:
            - versionExist
        spec:
            ...
```

### Alternatives you've considered

In my opinion a condition shouldn't be link to a target but link to an `action`

```
conditions:
    versionExist:
        kind: yaml
        # actionID means the condition is only a requirement for the pipeline linked to the actionID
        actionid: github
        spec:
            ...
targets:
    version:
        kind: yaml
        spec:
            ...
actions:
    github:
        kind: github/pullrequest
```

**Comment by dduportal** [comment]
I really like the proposal from @dcoraboeuf:

An updatecli target means "changing a file or a set of file": having conditions to control wether or not to run the change is pretty logic
  - I'm not sure why would you want to conditionalize an action as it maps to "do something with locally changed file so that it is remote". Do you have a use case in mind @olblak?
  - The ability to attach condition to both targets or actions is appealing though. But clearly, not being able to apply conditions on targets looks bad to me


Thinking with the target scenario, there are some UX question though:

- What would be the behavior of a target without the `conditions` keyword? 
  - Implicit "ALL" conditions as for today,
  - or explicit conditions as a new behavior?

**Comment by olblak** [comment]
I must admit the condition on the target makes more sense but my usecase remains the same, being able to have multiple action targeting different git repositories.

But in my case, I always managed to move that condition step to the "source" stage, so the source would only returns the value that I am looking for such as:

```sources:
    golangModuleVersion:
        name: Get latest golang module golang.org/x/mod version
        kind: golang/module
        spec:
            module: golang.org/x/mod
            versionfilter:
                kind: semver
                pattern: v0.11.0 || >0.11 < 1
targets:
    golangModuleVersion:
        name: Update golang.org/x/mod Golang module version
        kind: golang/gomod
        spec:
            file: go.mod
            module: golang.org/x/mod
        scmid: default
        sourceid: golangModuleVersion
```

where I am looking for a minor version update otherwise I fallback to `v0.11.0` which is the current value being used in my target

**Comment by olblak** [comment]
So I would be interested by a specific usecase

**Comment by dcoraboeuf** [comment]
Thanks for the issue and the discussion.

As for a use case, I find myself in the following situation:

* upon a release, we have 2 files to update
* one of these files, we have to update all the time
* but the second file, as per the existing delivery process, we may have to update or not, based on some human-based decision

The "updatecli" process is actually run manually at release time and the operator will have to decide if yes or no the second file has to be changed.

Technically, I can put the result of this decision in an environment variable and I can have a condition based on this environment variable being set or not (using a `shell` resource).

However, I need this condition to be applied to only one target. The rest of the pipeline (the other targets and my final action, the creation of a PR in my case, remains the same).

Of course, if there would be another way to achieve this scenario, I'm all for it. In the meantime, I've extracted this logic into a target based on a `shell` resource but that's a bit of a pity since I need to recode the update of the file itself (it's a Toml file) instead of relying on the `updatecli` definition.

**Comment by hervelemeur** [comment]
> if there would be another way to achieve this scenario, I'm all for it

As a workaround, you could have two manifests, one always updating the file and the other conditionnally updating the other file.

**Comment by dcoraboeuf** [comment]
> > if there would be another way to achieve this scenario, I'm all for it
> 
> As a workaround, you could have two manifests, one always updating the file and the other conditionnally updating the other file.

I like this :)

**Comment by dduportal** [comment]
> > if there would be another way to achieve this scenario, I'm all for it
> 
> As a workaround, you could have two manifests, one always updating the file and the other conditionnally updating the other file.

This workaround  remind me a brainstorming discussion I had with @gounthar a few days ago and one of the ideas that surfaced was: "could we share sources across pipelines? But only sources". With the following ideas:

- sources can take some time to be retrieved (I'm watching you `gittag` with nginx or ruby repositories... :D ), so when a big run of updatecli is executed, being able to reuse sources could gain a few seconds and resources

- The conditions could stay as it is today (please note that it is not mutually exclusive with the outcome of this "conditionnal target" issues) but you would have pipeline driven by the condition set (so 2 pipelines in your case @dcoraboeuf ) sharing the same source.
  - Pros: controling execution outcome would be easier: different exit codes and stdout for each pipeline to get a clear diagnostic of "what changed, what failed, what was skipped"
  - Cons: have to write to files and reference a common source


Food for though: @olblak I'm sure that is something you though about months (year?) ago

**Comment by gounthar** [comment]
> This workaround remind me a brainstorming discussion I had with @gounthar a few days ago and one of the ideas that surfaced was: "could we share sources across pipelines? But only sources". 

I think it was during our discussion on how to keep various Alpine-based images (such as Python, Ruby, PHP, Golang, etc.) up to date.
For each manifest, we would need to find the latest version for the specific language and then for Alpine in order to compose a Docker tag like `ruby:3.2.2-alpine3.18`.
Having a reliable source for Alpine information for several pipelines could greatly expedite the completion of these tasks.

**Comment by olblak** [comment]
As Herve suggested, I usually go with different manifests using the same `pipelineid`.
-> https://github.com/updatecli/website/issues/542
This allow me to express different pipeline behavior while targeting the same pullrequest when I need to group change in an atomic operation.

----

> Food for though: @olblak I'm sure that is something you though about months (year?) ago

Ho yeeeeeah.

What you suggest would contribute to two different areas 

1. Performance: Running tasks in parallel would drastically improve the performance
Because Updatecli usually run in a CI, the performance is not something that bother me a lot and we can improve everything at the same time.
2. UX: having to duplicate the same resource across manifest is really annoying.
This one really bother me, we already have open issues for that

I've been thinking to solve those two problems for a quite long time, but until today I didn't find one that I was happy with:

At the moment Updatecli is design with one manifest equal one pipeline.
Being able to executed pipeline in parallel for performance reason or cross reference means we need to identify each resource with a unique ID 

1. [performance] Similarly to scm, build a DAG of resources and then execute them in parallel.
2. [performance, UX] Reuse resource result across pipeline and only re-execute a  source/condition/target if the result is older than X
3. [UX] Moving that complexity to the DSL
  a. [UX] Cuelang has some interesting approach to templating
  b. [Performance, UX] HCL solved that problem but I really struggle to use it in the past

With my current experimentation about building a webapp, being able to identify resources is critical to me atm. 
Hence https://github.com/updatecli/updatecli/pull/1395

**Comment by dduportal** [comment]
> As Herve suggested, I usually go with different manifests using the same `pipelineid`. -> [updatecli/website#542](https://github.com/updatecli/website/issues/542) This allow me to express different pipeline behavior while targeting the same pullrequest when I need to group change in an atomic operation.
> 
> > Food for though: @olblak I'm sure that is something you though about months (year?) ago
> 
> Ho yeeeeeah.
> 
> What you suggest would contribute to two different areas
> 
>     1. Performance: Running tasks in parallel would drastically improve the performance
>        Because Updatecli usually run in a CI, the performance is not something that bother me a lot and we can improve everything at the same time.
> 
>     2. UX: having to duplicate the same resource across manifest is really annoying.
>        This one really bother me, we already have open issues for that
> 
> 
> I've been thinking to solve those two problems for a quite long time, but until today I didn't find one that I was happy with:
> 
> At the moment Updatecli is design with one manifest equal one pipeline. Being able to executed pipeline in parallel for performance reason or cross reference means we need to identify each resource with a unique ID
> 
>     1. [performance] Similarly to scm, build a DAG of resources and then execute them in parallel.
> 
>     2. [performance, UX] Reuse resource result across pipeline and only re-execute a  source/condition/target if the result is older than X
> 
>     3. [UX] Moving that complexity to the DSL
>        a. [UX] Cuelang has some interesting approach to templating
>        b. [Performance, UX] HCL solved that problem but I really struggle to use it in the past
> 
> 
> With my current experimentation about building a webapp, being able to identify resources is critical to me atm. Hence #1395

Note that I'm only scoping this to **sources** (not all resources). That would probably mean to have an explicit reference, something like this:

```
sources:
  alpineVersion:
    external: ./updatecli/updatecli.d/another-pipeline.yaml # The reference pipeline must have a source which id the same, eg. `alpineVersion`

targets:
# ...
``` 


The parallelization is a bigger topic and we could immediatly benefit in performance and UX with "only the sources without having to refactor the whole pipeline tree execution (I don't say we shouldn't, I'm just saying we can already benefit with a tighter scope)

**Comment by olblak** [comment]
We heavily diverged from the condition target :D 
To come back the the current issue, the current workaround is to have different manifest using the same pipelineid.

-----

Regarding major refactoring we need define what is the most important between UX vs Performance

@dcoraboeuf looks more UX while @gounthar sounds performance issues

I also have concerned to end up in a local optimum just by focusing on "source"
Last time I experimented with the current problematic was in this issue https://github.com/updatecli/updatecli/issues/430#issuecomment-1342652955

Back then, my concern was to re-implement in Updatecli something which I think should be handled at the DSL level. 🤷🏾

**Comment by olblak** [comment]
That being said, @dcoraboeuf suggestion looks good to me  and wouldn't require a large refactoring

```
targets:
    version:
        kind: yaml
        conditions:
            - versionExist
        spec:
            ...
```

maybe I would use `conditionids` to look like more `scmid` or `sourceid`

If conditionids is undefined then we fallback to all specified conditions otherwise we limit to listed conditionids

**Comment by dcoraboeuf** [comment]
If a target points, through `conditionids` to a condition defined in the global conditions under `conditions`, would that condition be counted in the global evaluation? IMO, if a condition is used by a target, it should not be used for the global pipeline.

That's why I was thinking about putting the specific condition directly under the target definition to simplify the understanding of the pipeline logic (like in my preview PR at #1382). This way, there is no need to use references. Of course, if a condition would need to be reused between several targets, that'd be not possible.
