### ISSUE TITLE
Feature Request: Support Github Enterprise

### ISSUE THREAD

**Issue by mekhanique** [updatecli/updatecli#1594]
### Is your feature request related to a problem?

Your tool looks awesome!  Unfortunately, I can't use it.  We use an internally hosted Github Enterprise instance and would need support for that in order to do so.  I'd open a PR myself, but my company doesn't allow me to do such things for legal purposes.

### Solution you'd like

Be able to add a property indicating a local server URL from which to base all other GitHub related actions.

### Anything else?

Nope.  Thanks again for writing this.  I hope this is something you'll have a chance to get to at some point soon.  Cheers!

**Comment by olblak** [comment]
@mekhanique Thanks for your interest in the project. You are right to ask question as I am having a hard time to keeping up on the documentation.

As a none GitHub enterprise user, I don't have working example but since  https://github.com/updatecli/updatecli/issues/862 I am aware of a few organization using it 

I just noticed that parameter documentation is broken at the moment https://www.updatecli.io/docs/plugins/actions/github/ and probably since the last release. It should be generated out of the code.

But IDE integration still work as expected, for example if you put your manifest in the directory `updatecli.d` vscode will suggest available parameters by run `ctrl-space` 

![image](https://github.com/updatecli/updatecli/assets/2360224/66a2edcf-eda4-4489-ae8e-4d8157de0169)
 


Well it appears that this page https://www.updatecli.io/docs/plugins/actions/github/ is missing parameters

**Comment by olblak** [comment]
Feel free to close once you can confirm that your issue is solved

**Comment by olblak** [comment]
Website is now fixed https://www.updatecli.io/docs/plugins/scm/github/

Feel free to reopen if it doesn't work for you

**Comment by mekhanique** [comment]
Thanks! I'll give it a try!  Appreciate the fast response too!
