### ISSUE TITLE
Enable autocompletion for updatecli CLI

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#286]
**Is your feature request related to a problem? Please describe.**

I'm always mixing updatecli flags with other CLI tools flags, leading on retrying multiple time when calling updatecli CLI.

**Describe the solution you'd like**

I would want an autocompletion on my shells (bash and zsh) for updatecli CLI.

As cobra is used on its latest stable version, it looks like that <https://github.com/spf13/cobra/blob/master/shell_completions.md> could be used.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by gcuisinier** [comment]
After verification, the autocompletion is working in bash by doing 

```
source <( updatecli completion bash )
```
But you need a recent bash (the default one in OSX seems too old) and bash completion.


In zsh, it's not working from scratch by doing 
```
source <( updatecli completion zsh )
```

Root cause is that the generated content  by Cobra does not allow the sourcing in this way as it seems not a good practice for perfomance issue.
(root cause is that commented line : #compdef _updatecli updatecli )

By checking to other cli, there are multiple workaround 

- Override the default completion command to enable the sourcing way
- Create a proper completion content in $FPATH, in general done in the homebrew recipe, and provide the installation step as message at the end of the installation 

I can also just add a documentage page for the autocompletion somewhere in the  doc ( https://www.updatecli.io/docs/prologue/installation/ maybe ? )

**Comment by olblak** [comment]
Since [v0.40.2](https://github.com/updatecli/updatecli/releases/tag/v0.40.2)
Autocompletion is now configured automatically when installing via `.rpm`, `.deb`, or homebrew.
