### ISSUE TITLE
Feature Request: add "createdForVersion" metadata

### ISSUE THREAD

**Issue by lemeurherve** [updatecli/updatecli#367]
**Is your feature request related to a problem? Please describe.**
When new updatecli features are implemented, there is no easy way to find the updatecli configurations which could implement them so they can be updated/refactored.

**Describe the solution you'd like**
Adding a metadata/field `createdForVersion` (or `createdFromVersion`?) to the updatecli configuration files would allow to find when/which version of updatecli was taken in account when creating the config files, and thus allow to identify old ones so they can be updated/refactored.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by olblak** [comment]
Since updatecli version `0.27.0`, it's now possible to use `updatecli manifest upgrade --config example.yaml` to upgrade the syntax to the current updatecli version
 
Introduced in that release, the key "version" can be used to specify the minimum version required. You can find an example [here|https://github.com/updatecli/website/blob/8f1fe8ba78626acb45d573804a2b406c71c83de1/updatecli/updatecli.d/installation.yaml#L47]

Please note that if you run `updatecli manifest upgrade --config updatecli.d` it will automatically set the version to the current updatecli version used
