### ISSUE TITLE
Change non absolute paths to resource to be relative to YML manifest instead of current working dir?

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#410]
**Is your feature request related to a problem?**
 
As underlined by @olblak in https://github.com/updatecli/updatecli/pull/388#issuecomment-991077726, the relative path for resources is resolved from the directory where the command `updatecli` command is run (e.g. the "current working directory").

This behavior is problematic as soon as you change this "current working dir": either you're browsing from a subdirectory or using absolute path.

Example, with the following YAML manifest:

```yaml
# config.yaml
sources:
  readFromFile:
    kind: file
    spec:
      file: ./updatecli/file.txt
targets:
  printsContent:
    kind: shell
    spec:
      # Echoes the source value
      command: echo
```

```shell
$ cat updatecli/file.txt 
Hello
$ tree ./updatecli
./updatecli
├── config.yaml
├── file.txt

## Success
$ updatecli diff --config ./updatecli/config.yaml

# ...
SOURCES
=======

readFromFile
------------
✔ Content: found from file "./updatecli/file.txt":
Hello
# ...

## Failure because relative path
$ cd ./updatecli/
$ updatecli diff --config ./config.yaml

# ...
SOURCES
=======

readFromFile
------------
ERROR: ✗ Validation error: the provided manifest configuration had the following validation errors:
Invalid spec for yaml resource: the file "./updatecli/file.txt" does not exist.
# ...

## Failure because relative path
$ cd ..
$ PROJECT_DIR=$(pwd)
$ cd /tmp
$ updatecli diff --config "${PROJECT_DIR}"/updatecli/config.yaml

# ...
readFromFile
------------
ERROR: ✗ Validation error: the provided manifest configuration had the following validation errors:
Invalid spec for yaml resource: the file "./updatecli/file.txt" does not exist.
# ...
```

**Describe the solution you'd like**

It would make sense to resolve relative path from the YAML manifest files provided as config: it would solve all the issues here.

**However** that would break a lot of actual configurations.

**Describe alternatives you've considered**
N.A.

**Additional context**
Trying to be "smart" by trying to autodetect if the path would wether be "relative to manifest, otherwise to CWD" could be risky (weird "magical" code).

**Comment by lemeurherve** [comment]
There seem to be some copy/pastes left behind, all 3 updatecli commands are the same currently.

**Comment by lemeurherve** [comment]
This FR seems a little bit too magic to me, is there other cli tools with the same behavior?

**Comment by dduportal** [comment]
edit: updated the pull request message to ensure the example is clearer. WDYT @lemeurherve ?

**Comment by olblak** [comment]
> This FR still seems a little bit too magic to me, is there other cli tools with the same behavior?

What do you mean by "FR"? :p 
Right now we have two behaviors, one that interact with a git repository and a second which don't

The workflow without git repository interaction is quite simple. It looks at the path(absolute or relative) defined in the manifest. The relative path is evaluated from where the cli is called. I agree that evaluating the path from the manifest would be better.

The second workflow is when we interact with a git repository, in that case, updatecli clone every git repository in a temporary location, do all the things needed such as creating temporary branches, changing files, commits, push, etc. and then it deletes the directory. This approach is quite convenient for git operations because we start from a "fresh" environment.
In this second approach validating that the file exists can't be done initially because the git repository hasn't been cloned yet, hence the current error and then we need to change the "working directory" to where the repository was cloned 

@damien open the issue #262 to replace/improve the second workflow by a new one where instead of cloning the git repository in a temporary location we would use the local one. While I agree that having a local mode would be super  useful, I still have several concerned.

**Comment by dduportal** [comment]
> What do you mean by "FR"? :p

FR for "Feature Request" I guess?

**Comment by dduportal** [comment]
> In this second approach validating that the file exists can't be done initially

Validation isn't able (with updatecli 0.16 at least) to access the resource's context: it only has access to the content of the decoded "spec" (no access to an eventual "scm" or to the configuration tree to know if it's a source, a condition or a target). That's the reason why no "SCM specific" validation was implemented at first.

Fixing the validation system by making it happen with al lthe requried parsed content would solve the issue, independantly of the "scm / local" discussion.

**Comment by olblak** [comment]
@dduportal I have been hit by this issue again.
Do you have any objection to me commenting the code that checks if a file exists locally?

**Comment by olblak** [comment]
This affect the three resources "yaml,file, dockerfile"

**Comment by dduportal** [comment]
@olblak do you mind sharing the failing example in the PR if you do so? But yes go ahead if it helps you

**Comment by olblak** [comment]
> @olblak do you mind sharing the failing example in the PR if you do so? But yes go ahead if it helps you

I was testing some documentation where I say "copy this updatecli to your machine" then run "updatecli --config manifest.yaml" but it would fail because it tests if a file exists before cloning the git repository in the `tmp` directory.

**Comment by dduportal** [comment]
> I was testing some documentation where I say "copy this updatecli to your machine" then run "updatecli --config manifest.yaml" but it would fail because it tests if a file exists before cloning the git repository in the tmp directory.

Can you share the example? It's important to explain for ourselves the reason of doing this change.
