### ISSUE TITLE
SCM/Source ID case insensitivity

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#444]
**Is your feature request related to a problem?**

We should be able to specify `sourceID` as well as `Sourceid`.
Same for scm ids.

**Comment by lemeurherve** [comment]
I would even go a little further and remove all "...id" which don't add anything semantically and are just (IMHO) cumbersome.

**Comment by dduportal** [comment]
Good idea.

**Comment by olblak** [comment]
While experimenting with jsonschema validation, I realize that this issue is a blocker.
The current state is not consistent and It would be better to have everything lowercase

Current jsonschema validation warning
```
Property sourceID is not allowed.
Property scmID is not allowed.
```

I like @lemeurherve suggestion by replacing `sourceID` by `source` but I have mix feeling for replacing `scmID` by `scm` because `scm` is a existing deprecated field.

**Comment by olblak** [comment]
@dduportal Any opinion?

**Comment by dduportal** [comment]
As a maintainer, I understand the need to make it all lowercase.

As a end-user, if my current syntax `scmId` does not work anymore, then it is a breaking change that is not really acceptable (I expect the parser to manage all syntaxes OR to have a command that allows me to correct it one time).

**Comment by olblak** [comment]
Introducing breaking change is not an option to me. 
I am considering printing a warning if `scmID` or `sourceID` are used instead of the lowercase equivalent `scmid` or `sourceID`

The work that  I am doing with jsonschema validation won't be enforced. If your IDE is configured with the updatecli json schema, like I have at the moment for experimenting, it would trigger error messages such as 

```
Property sourceID is not allowed.
Property scmID is not allowed.
```
But existing updatcecli configuration would still run.

**Comment by dduportal** [comment]
> Introducing breaking change is not an option to me. I am considering printing a warning if `scmID` or `sourceID` are used instead of the lowercase equivalent `scmid` or `sourceID`
> 
> The work that I am doing with jsonschema validation won't be enforced. If your IDE is configured with the updatecli json schema, like I have at the moment for experimenting, it would trigger error messages such as
> 
> ```
> Property sourceID is not allowed.
> Property scmID is not allowed.
> ```
> 
> But existing updatcecli configuration would still run until we fully remove none lowercase fields.

That sounds really cool! GO for it then!
