### ISSUE TITLE
Feature Request: give a way to capture source part with MatchPattern

### ISSUE THREAD

**Issue by smerle33** [updatecli/updatecli#517]
### Is your feature request related to a problem?

I though I could use matchPattern from within sources to get a specific capture on a multi line regexp but it seems not to work as expected. 

`matchPattern: "aws_security_group.*\n.*name.*\"(.*)\".*\n.*infra\\.ci"`

(the regexp as been tried on regexp101.com as golang flavor with success)

let me assume that the source.SOURCENAME would be the captured part of the regexp "(.*)" but ... it's not ....

### Solution you'd like

get an option -regexpSubstr for example that allow regexp capture
I also tried the 
`transformers:
      - findSubMatch: 'name.*"(.*)"'`
   
with no luck

### Anything else?

I am probably mystaking something somewhere but no way to find out ... and it seems related to the multiline concept

**Comment by olblak** [comment]
Hi, 
I thought it was already working
Have you tried using "findSubMatch"

**Comment by olblak** [comment]
Ha I missed that you already tried findSubMatch, I need to check

**Comment by smerle33** [comment]
Hi,
I see 2 ways of solving this within the transformers, 
   - first, just change line : https://github.com/updatecli/updatecli/blob/5afdcfbc0c5f1ca88ebef3da3ec876ada884ed8a/pkg/core/transformer/main.go#L127 with output = found[1] (instead of output = found[0])
   
   - second, offering the opportunity to choose the slice index that may be return by adding a parameter to the call to findSubMatch and then findSubMatch may look like replace ....

**Comment by dduportal** [comment]
After discussions with the 2 of you, here is the proposal:

- (new feature) Allow to specify the index of the capture. It means that the transformer does not return the matched line, but **only** 1 capture. No more, no less.

```yaml
transformers:
  - findSubMatch: 
      # Note that it is indented, like the "replace"
      pattern: '"(.*?):(.*)'
      captureIndex: 1
```

- (new feature) Introduces a `findLine` transformer which behaves the same as the actual `findSubMatch` but with a clearer naming: it returns the line(s) matched by the provided regexp pattern.

```yaml
transformers:
  - findLine: '^key:.*$' # Returns all lines matching the provided pattern
```

- (Avoid breaking change) The parser for the new `findSubMatch` introduced above should handle the actual case (a string is passed to the key `findSubMatch` instead of a map). In that case, a warning should be shown to the user, recommending to either look at `findLine` or to specify the `pattern` and `captureIndex`. But it would keep working by setting these 2 attributes with `captureIndex` set to zero:

```yaml
transformers:
  - findSubMatch: '"(.*?):(.*)' # Trigger a warning
```

would be equivalent (with the warning message) to:

```yaml
transformers:
  - findSubMatch: 
      pattern: '"(.*?):(.*)'
      captureIndex: 0
```

**Comment by lemeurherve** [comment]
LGTM :)


> (new feature) Allow to specify the index of the capture. It means that the transformer does not return the matched line, but only 1 capture. No more, no less.

OK about capturing only one group/capture, but what about the case when there are more than one line matching the pattern?

> transformers:
>   - findLine: '^key:.*$' # Returns all lines matching the provided pattern

I would name it findLines if it can return more than one line.

**Comment by dduportal** [comment]
> I would name it `findLines` if it can return more than one line.

LGTM 👍

**Comment by dduportal** [comment]
> OK about capturing only one group/capture, but what about the case when there are more than one line matching the pattern? It would return an array of the group/capture found on every line?


Could you provide an example, I'm not sure how it would be (and should behave). I would have expected (naively maybe) that the captures are ordered so the index would take care of this? But I might misunderstand.

**Comment by lemeurherve** [comment]
Yes that what I had in mind, I've just wanted to be sure this case wouldn't be forgotten.
