### ISSUE TITLE
Feature Request: Add jsonschema to validate updatecli configuration

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#524]
### Is your feature request related to a problem?

It would be useful to have a JSON schema to validate updatecli configuration from an IDE.
More information on https://json-schema.org/specification.html

### Solution you'd like

I would like to easily write updatecli configuration from VScode

**Comment by olblak** [comment]
After some investigation, it seems that the best approach would be to write the JSON files as documented on https://json-schema.org/

Once written, we'll be able to import the schema into IDE so it will be easier to write \updatecli configurations. 
Itt will also be useful for implementing a validate option to validate manifest without loading them, such as 
`updatecli validate --config updatecli.yaml`

**Comment by olblak** [comment]
Here is an update of my experimentation regarding Json schema.
As a reminder, my initial motivation was to use Json Schema with IDE, to simplify creation and maintenance of updatecli manifests.

While looking into this, I realized that not only it would be useful to use those schema in IDEs but also to automatically generate reference documentation for www.updatecli.io, and quickly validating updatecli manifest from a command line such as `updatecli validate --config updatecli.d`.

To be more familiarized with Json schema, I firstly tried to write them myself, then I looked into other approaches

## Independent DSL

In this approach, we have to write Json schema our-self with a separated life-cycle than the code.

### github.com/santhosh-tekuri/jsonschema

The library is easy to use but we need to put in place processes to test written Json schema
I wrote a test to validate that Updatecli manifests from e2e were still working. I was able catch most of the errors automatically.
The downside is before writing any golang code, we would need to write json schema which implies additionnal knowledge.

The code is available on https://github.com/olblak/updatecli/tree/jsonschema, especially in the schema directory

+ :
* We can define complex Json schema

- :
* We have to maintain both Golang code and Json schema
* Risk to have outdated Json schema
* There is a bigger initial work to do for writing schema.

## DSL to code

I didn't spend much time experimenting with libraries that allow to generate Golang struct based on Json schema.
The main reason is because we have a specific way to organize the code between plugin resources and the resource interface.

## Code to DSL

In this approach, we wouldn't have to write or care about Json schema. It would be automatically generated based on the existing Golang code.
I did some experimentation with the following libraries.

### github.com/mcuadros/go-jsonschema-generator

It's a very basic one. It doesn't generate description based on comments. It doesn't have "condition" such as "if" or "oneOf" 
The invopop/jsconschema is better in every situation.

### github.com/invopop/jsonschema

It's a very promising library closed to what I am looking for **but** I couldn't make it works correctly.
It doesn't handle very well the way we rely on condition such as if kind == jenkins then Jenkins spec, if kind == maven then maven spec, etc..
While the library is easy to grasp, I think it would implies some major refactoring in updatecli code base about the way we manage specific struct based on the kind. And I am not convinced that the time investment need is worthwhile at the moment.

An example of schema generated is available on https://gist.github.com/olblak/0c1a9fdfca03b7ec27ca25ea1bcc2dc8
The generated schema is very basic.


## Additional information

I also briefly looked look at cuelang, openapi, dhall but they don't seem to be what I am currently looking for 


In the current state,  I would be more in favor to write json schema using santhosh-tekuri/jsonschema library
@dduportal  any thoughts?

**Comment by olblak** [comment]
In fact, the two branches are not mutually exclusive since one is about generating JSON schema, while the other is about validating updatecli configuration using manually written JSON schema

**Comment by dduportal** [comment]
To summarize our discussions:

- This is really usefull, no doubt about that. If this change is merged, then it adds value *right now*.
- Manually managed means that there will be a drift beetween the reality and the JSON schema (we always have a BIG gap between reality and documentation: that will be exactly the same pattern), unless we have automation.
- Once we will have some drift, that means "maintainer spending time to fill the gap instead of adding more value at that time".
- Manually managed also means: a steeper curve for contributors

Somehow, it's a gamble: do you bet that you can add value right now and cross fingers that a solution will be found (or that the drift gap might stay small and un-noticeable for end users)?

My vote is in favor of "not adding it manually" because both you and I, the 2 principals maintainers, aren't able to keep up with the feature requests, and aren't able to keep up with documentation drift as for today because our hands are full.

I would change my vote to "yes go for it" under any of the the following events:

- If we have a user feedback (a real one: at least 3 users) asking for the JSON schema no matter what 
- Or if we have a 3rd *regular* maintainer: It would be sustainable to add json support manually.
- Or if we find a way to automate the JSON generation

**Comment by olblak** [comment]
This work is currently on hold, so I remove the targeted milestone
