### ISSUE TITLE
Feature Request: Improve templating system observability

### ISSUE THREAD

**Issue by lemeurherve** [updatecli/updatecli#954]
### Is your feature request related to a problem?

It can be difficult to debug what's wrong with a template, last example in date: https://github.com/jenkins-infra/aws/pull/201

### Solution you'd like

Adding debug logs when rendering the templated manifests (with {{}} forms)

### Alternatives you've considered

Desk head banging

**Comment by olblak** [comment]
I agree that templating at run time is difficult. I usually first go with `updatecli manifest show --config updatecli/updatecli.d/updatecli.yaml` my concerned is about leaking credentials but I guess a warning at the beginning of a pipeline such as 

```
Running Updatecli in Debug mode can on purpose leak credentials
``` 

We could also display resource spec before a run

**Comment by olblak** [comment]
With the more advance templating capabilities introduced in 0.57.0, this issue is more relevant than never.
A manifest can go through multiple stage before being ready for templating such as:

.1 Merge all `--values` and `secrets` together

Updatecli first merge all the values together and then secrets which ensure that secrets information take precedence.
worth mentioning the merge only merge the first level. Differently said, it doesn't do deep merge on purpose...

.2 Load raw manifest specified by `--config`
.3 Execute the Go templated using the values informations
.4 Parse the generated file by the YAML/Json parser

Because of such, the generated Manifest must be YAML compliant and the `values`/`secrets` are not templated

In the current stage, the Updatecli debug information only show the manifest generated after stage 4 which can be really cumbersome to understand.

My only concern is by using the flag --debug, we'll show a lot of information to the like the raw file, the templated file, and after go through the YAML parsing.
Therefor I am considering adding a new flag `--trace`
